### ISSUE TITLE
Erro ao rodar ng serve no projeto de rotas

### ISSUE THREAD

**Issue by alexandrenilton** [loiane/curso-angular#62]
Após baixar o projeto de rotas do repositório e instalar as dependencias (npm install) e tentar rodar o ng serve aparece os erros abaixo:
`PS C:\dev\curso-angular-2-loiane\rotas> ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 92% additional asset processing scripts-webpack-plugin× ｢wdm｣: Error: ENOENT: no such file or directory, open 'C:\dev\curso-angular-2-loiane\jquery\dist\jquery.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Storage.provideSync (C:\dev\curso-angular-2-loiane\rotas\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (C:\dev\curso-angular-2-loiane\rotas\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:259:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (C:\dev\curso-angular-2-loiane\rotas\node_modules\@ngtools\webpack\src\webpack-input-host.js:35:51)
    at Observable.subscribe (C:\dev\curso-angular-2-loiane\rotas\node_modules\@ngtools\webpack\node_modules\rxjs\internal\Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (C:\dev\curso-angular-2-loiane\rotas\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:22:20)
    at SyncDelegateHost.read (C:\dev\curso-angular-2-loiane\rotas\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (C:\dev\curso-angular-2-loiane\rotas\node_modules\@ngtools\webpack\src\compiler_host.js:125:44)
    at VirtualFileSystemDecorator.readFile (C:\dev\curso-angular-2-loiane\rotas\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:39:54)
    at Promise (C:\dev\curso-angular-2-loiane\rotas\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:69:49)
    at new Promise (<anonymous>)
    at scripts.map.fullPath (C:\dev\curso-angular-2-loiane\rotas\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:68:24)
    at Array.map (<anonymous>)
    at CachedInputFileSystem.readFileSync (C:\dev\curso-angular-2-loiane\rotas\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:259:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (C:\dev\curso-angular-2-loiane\rotas\node_modules\@ngtools\webpack\src\webpack-input-host.js:35:51)
    at Observable._trySubscribe (C:\dev\curso-angular-2-loiane\rotas\node_modules\@ngtools\webpack\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\dev\curso-angular-2-loiane\rotas\node_modules\@ngtools\webpack\node_modules\rxjs\internal\Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (C:\dev\curso-angular-2-loiane\rotas\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:22:20)
    at SyncDelegateHost.read (C:\dev\curso-angular-2-loiane\rotas\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (C:\dev\curso-angular-2-loiane\rotas\node_modules\@ngtools\webpack\src\compiler_host.js:125:44)
    at VirtualFileSystemDecorator.readFile (C:\dev\curso-angular-2-loiane\rotas\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:39:54)
    at Promise (C:\dev\curso-angular-2-loiane\rotas\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:69:49)
    at new Promise (<anonymous>)
    at scripts.map.fullPath (C:\dev\curso-angular-2-loiane\rotas\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:68:24)
    at Array.map (<anonymous>)
    at hook (C:\dev\curso-angular-2-loiane\rotas\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\scripts-webpack-plugin.js:67:43)`

**Comment by alexandrenilton** [comment]
Para corrigir isso, apenas alterei as linhas 27, 28 e 29 do angular.json:
Tirando: 
`"../jquery/dist/jquery.js",
"../hammerjs/hammer.js",
"../materialize-css/dist/js/materialize.js"`
Trocando para: 
`"node_modules/jquery/dist/jquery.js",
 "node_modules/hammerjs/hammer.js",
 "node_modules/materialize-css/dist/js/materialize.js"`
